---
# SweetPotatOs branding
style:   widget
slideshow: false

welcomeStyleCalamares:   true
welcomeExpandingLogo:    true

windowExpanding:         right
windowPlacement:         center

sidebar: widget

strings:
    productName:         SweetPotatOs
    shortProductName:    SweetPotatOs
    version:             2026
    shortVersion:        2026
    versioned:           SweetPotatOs 2026
    shortVersioned:      SweetPotatOs 2026
    bootloaderEntryName: SweetPotatOs
    productUrl:          https://github.com/
    supportUrl:          https://github.com/
    knownIssuesUrl:      https://github.com/
    releaseNotesUrl:     https://github.com/
    donateUrl:           https://github.com/

images:
    productLogo:         "logo.png"
    productIcon:         "icon.png"
    productWelcome:      "welcome.png"

colors:
    sidebarBackground:   "#1d1f21"
    sidebarText:         "#ffffff"
    sidebarTextCurrent:  "#f79b29"
    sidebarBackgroundCurrent: "#a73b50"
