---
# GRUB for UEFI/BIOS
efiBootLoader: "grub"
biosBootLoader: "grub"

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubSetup: "grub-install"

efiBootLoaders:
    "/boot/EFI/BOOT/BOOTX64.EFI": "grubx64.efi"
    "/boot/EFI/BOOT/BOOTIA32.EFI": "grubia32.efi"

installEFIFallback: true

grubCfg: "/etc/default/grub"

updateNvram: true
