---
# Ensure /etc/default/grub exists and has sensible defaults before grub-mkconfig.
overwrite: false
prefer_grub_d: false
keep_distributor: false
kernel_params: [ "quiet", "splash" ]

defaults:
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: "saved"
    GRUB_DISABLE_SUBMENU: true
    GRUB_TERMINAL_OUTPUT: "console"
    GRUB_DISABLE_RECOVERY: "false"
