---
# Remove live-environment packages from the installed system
remove:
    - calamares
    - arch-install-scripts
    - mkinitcpio-archiso
    - mkinitcpio-nfs-utils
    - darkhttpd
    - memtest86+
    - memtest86+-efi
    - syslinux
    - edk2-shell
    - livecd-sounds
    - nbd
    - ndisc6
    - nfs-utils
    - testdisk
    - clonezilla
    - cloud-init

tryRemove:
    - virtualbox-guest-utils-nox
    - open-vm-tools
    - qemu-guest-agent
    - hyperv

operations:
    - remove
