---
services:
    targets:
        - multi-user.target
    services:
        - NetworkManager.service
        - ly@tty2.service
    disable:
        - iwd.service
        - systemd-networkd.service
        - systemd-networkd-wait-online.service
