---
# Do not recreate the live ISO user on the target system
defaultGroups:
    - users
    - wheel
    - audio
    - video
    - storage
    - optical
    - network
    - power
    - input

autologinGroup:  autologin
sudoersGroup:    wheel

doAutologin:     false

setRootPassword: true
doReusePassword: false

passwordRequirements:
    minLength: 1
    maxLength: -1

writeGenericMetadata: true
