---
showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false

requirements:
    requiredStorage:    8.0   # GB
    requiredRam:        1.0   # GB
    internetCheckUrl:   https://archlinux.org
    check:
        - storage
        - ram
        - power
        - internet
    required:
        - storage
        - ram
    optional:
        - power
        - internet

localeExpanderCollapsed: false
keyboardExpanderCollapsed: false

dontShowFinishedPage:   false
supportUrl:             https://github.com/
knownIssuesUrl:         https://github.com/
releaseNotesUrl:        https://github.com/
