[preferred]
default=gtk
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr
# xdg-desktop-portal-gtk's implementation uses org.gnome.SessionManager and
# org.freedesktop.ScreenSaver, neither of which is implemented by Swirl/Sway.
org.freedesktop.impl.portal.Inhibit=none
