---
# SweetPotatOs Calamares settings
modules-search: [ local ]

instances:
- id:       welcome
  module:   welcome
- id:       finished
  module:   finished

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - networkcfg
  - displaymanager
  - services-systemd
  - bootloader
  - packages
  - umount
- show:
  - finished

branding: sweetpotatoos

prompt-install: true
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: true

requirements:
  check:
    - storage
    - ram
    - power
    - internet
  required:
    - storage
    - ram
  optional:
    - power
    - internet
